### PR TITLE
prepare 0.3.1: fix containerImage field to v0.3.0

### PR DESCRIPTION
**Pull request by eguzki**
Diff 0.3.1 and 0.3.0

```
$ diff manifests/0.3.0/apicast-community-operator.v0.3.0.clusterserviceversion.yaml manifests/0.3.1/apicast-community-operator.v0.3.1.clusterserviceversion.yaml 
52c52
<     containerImage: quay.io/3scale/apicast-operator:v0.2.0
---
>     containerImage: quay.io/3scale/apicast-operator:v0.3.0
57c57
<   name: apicast-community-operator.v0.3.0
---
>   name: apicast-community-operator.v0.3.1
60c60
<   replaces: apicast-community-operator.v0.2.2
---
>   replaces: apicast-community-operator.v0.3.0
257c257
<     url: https://github.com/3scale/apicast-operator/tree/v3.8
---
>     url: https://github.com/3scale/apicast-operator/tree/v3.9
267c267
<   version: 0.3.0
---
>   version: 0.3.1
```

### CODE REVIEW

**Review by miguelsorianod — CHANGES_REQUESTED** [review]
Could you provide a diff output?

thanks

**Comment by eguzki** [comment]
Diff added

**Review by miguelsorianod — CHANGES_REQUESTED** [review]
I've noticed the `url` field contains:

```
url: https://github.com/3scale/apicast-operator/tree/v3.8
```

It would be good to fix this too.

**Comment by eguzki** [comment]
good catch. Updated diff

**Review by miguelsorianod — APPROVED** [review]

**Pull request merged**
