### PR TITLE
Prepare v0.2.1

### PR DESCRIPTION
**Pull request by eguzki**

### CODE REVIEW

**Review by miguelsorianod — CHANGES_REQUESTED** [review]
The base64 value of the icon seems different than what we have in the productized CSV

**Review by miguelsorianod — CHANGES_REQUESTED** [review]
See feedback

**Comment by eguzki** [comment]
It has been decided to be like that

**Comment by miguelsorianod** [comment]
:+1: .

I see, we have different icons (and their types too) between community and productized

**Review by miguelsorianod — APPROVED** [review]

**Pull request merged**
